### ISSUE TITLE
Getting to first release

### ISSUE THREAD

**Issue by MichelML** [rdkit/rdkit-js#21]
- [x] https://github.com/MichelML/rdkit-js/issues/22
- [x] https://github.com/MichelML/rdkit-js/issues/20
- [x] https://github.com/MichelML/rdkit-js/issues/19
- [x] https://github.com/MichelML/rdkit-js/issues/23
- [x] https://github.com/MichelML/rdkit-js/issues/28
- [x] #117 
- [x] https://github.com/MichelML/rdkit-js/issues/24

Remaining tasks before closing this:

- [x] Bring the idea of another name because of history to Greg and others (rdkit-mini? rdkit-wasm?)
- [x] Explain state of repository to Greg and others
- [x] License review and suggest Valence Discovery in license
- [x] Ask how should this be merge/transfer
- [x] Bring discussion for rdkit-structure-renderer of ptosco being developed and published in context of this project
- [x] Things to do post-transfer
    - [x]  Renaming github repo path reference from MichelML/rdkit-js to rdkit/rdkit-js
    - [x]  Adjust azure pipeline and related scripts
- [x] #127 (and fix broken parts)
- [x] #129 
- [ ] #130 
- [ ] #128

**Comment by MichelML** [comment]
Remaining tasks before closing this:

- [ ] Bring the idea of another name because of history to Greg and others
- [ ] Explain state of repository to Greg and others
- [ ] Suggest Valence in license
- [ ] Ask how should this be merge/transfer
- [ ] Bring rdkit-structure-renderer of ptosco in context of this project
- [ ] Things to do pre-transfer
    - [ ] Adjust pipeline pre-transfer to use the new versioning system suggested
- [ ] Things to do post-transfer
    - [ ]  Renaming github repo path reference from MichelML/rdkit-js to rdkit/rdkit-js
    - [ ]  Adjust azure pipeline and related scripts

**Comment by MichelML** [comment]
I think this can be closed, remaining issues will be completed as the project continue to evolve
